"""add message sequence number

Revision ID: 7af58a1df946
Revises: 3c1068922c5b
Create Date: 2026-08-17 15:12:47.511845

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7af58a1df946'
down_revision: Union[str, Sequence[str], None] = '3c1068922c5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('sequence_number', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_messages_created_at'), 'messages', ['created_at'], unique=False)
    op.create_unique_constraint('uq_messages_conversation_sequence', 'messages', ['conversation_id', 'sequence_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_messages_conversation_sequence', 'messages', type_='unique')
    op.drop_index(op.f('ix_messages_created_at'), table_name='messages')
    op.drop_column('messages', 'sequence_number')
    # ### end Alembic commands ###
